dist: xenial
language: scala
scala:
  - 2.11.12
  - 2.12.10
  - 2.13.0
jdk:
  - openjdk8
  - openjdk11
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
    - stage: test
      install:
        - npm install jsdom
      script: sbt ++$TRAVIS_SCALA_VERSION test
      cache:
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt
          - $HOME/.coursier
          - node_modules
    - stage: release
      name: "Cross-publish to Sonatype"
      before_install: git fetch --tags
      script: sbt ci-release
      cache:
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt/boot
          - $HOME/.coursier
before_cache:
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
