dist: bionic
language: scala
jdk: openjdk11
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
before_cache:
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
jobs:
  include:
#    - scala: 2.11.12
#      install:
#        - npm install jsdom
#      script: sbt ++$TRAVIS_SCALA_VERSION test
#      cache:
#        directories:
#          - $HOME/.ivy2/cache
#          - $HOME/.sbt
#          - $HOME/.coursier
#          - node_modules
#    - scala: 2.12.10
#      install:
#        - npm install jsdom
#      script: sbt ++$TRAVIS_SCALA_VERSION test
#      cache:
#        directories:
#          - $HOME/.ivy2/cache
#          - $HOME/.sbt
#          - $HOME/.coursier
#          - node_modules
#    - scala: 2.13.0
#      install:
#        - npm install jsdom
#      script: sbt ++$TRAVIS_SCALA_VERSION test
#      cache:
#        directories:
#          - $HOME/.ivy2/cache
#          - $HOME/.sbt
#          - $HOME/.coursier
#          - node_modules
    - stage: release
      name: "Cross-publish to Sonatype"
      before_install:
        - git fetch --tags
        - openssl aes-256-cbc -K $encrypted_de5ffdf9df6c_key -iv $encrypted_de5ffdf9df6c_iv -in .travis/secret-key.asc.enc -out .travis/secret-key.asc -d
        - echo $PGP_PASSPHRASE | gpg --passphrase-fd 0 --batch --yes --import .travis/secret-key.asc
        - gpg --list-secret-keys
      script: sbt ci-release
      cache:
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt/boot
          - $HOME/.coursier
