addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "0.6.1")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "0.6.1")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "0.6.29")

addSbtPlugin("com.dwijnand"     % "sbt-dynver"     % "4.0.0")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"   % "3.7")
addSbtPlugin("com.geirsson"     % "sbt-ci-release" % "1.3.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"        % "1.0.0")
//addSbtPlugin("com.jsuereth"     % "sbt-pgp"        % "2.0.1-M3")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.0.6")
