addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "1.0.0")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.0.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "1.3.0")

addSbtPlugin("com.dwijnand" % "sbt-dynver" % "4.1.1")
//addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"   % "3.8")
addSbtPlugin("com.geirsson"     % "sbt-ci-release" % "1.5.3")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"        % "1.0.0")
//addSbtPlugin("com.jsuereth"     % "sbt-pgp"        % "2.0.1-M3")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.2")
